# Development environment properties
spring.datasource.url=jdbc:postgresql://localhost/StudentAutomation
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
